"""Initial migration

Revision ID: 1ef2526c7d17
Revises: 
Create Date: 2025-08-05 22:53:38.958365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ef2526c7d17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postcode', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('profile_complete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('company_registration_number', sa.String(length=100), nullable=False),
    sa.Column('nature_of_business', sa.String(length=255), nullable=False),
    sa.Column('tax_id_number', sa.String(length=100), nullable=True),
    sa.Column('director_name', sa.String(length=255), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=False),
    sa.Column('contact_designation', sa.String(length=100), nullable=False),
    sa.Column('contact_email', sa.String(length=120), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('alt_contact_name', sa.String(length=255), nullable=True),
    sa.Column('alt_contact_designation', sa.String(length=100), nullable=True),
    sa.Column('alt_contact_email', sa.String(length=120), nullable=True),
    sa.Column('alt_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('reg_address_line1', sa.String(length=255), nullable=False),
    sa.Column('reg_address_line2', sa.String(length=255), nullable=True),
    sa.Column('reg_city', sa.String(length=100), nullable=False),
    sa.Column('reg_state', sa.String(length=100), nullable=False),
    sa.Column('reg_postcode', sa.String(length=20), nullable=False),
    sa.Column('reg_country', sa.String(length=100), nullable=False),
    sa.Column('op_address_line1', sa.String(length=255), nullable=False),
    sa.Column('op_address_line2', sa.String(length=255), nullable=True),
    sa.Column('op_city', sa.String(length=100), nullable=False),
    sa.Column('op_state', sa.String(length=100), nullable=False),
    sa.Column('op_postcode', sa.String(length=20), nullable=False),
    sa.Column('op_country', sa.String(length=100), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('bank_account_number', sa.String(length=50), nullable=False),
    sa.Column('registration_cert_path', sa.String(length=255), nullable=True),
    sa.Column('bank_verification_doc_path', sa.String(length=255), nullable=True),
    sa.Column('director_id_doc_path', sa.String(length=255), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_registration_number'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplier')
    op.drop_table('customer')
    op.drop_table('user')
    # ### end Alembic commands ###
